Repository dadi/cdn, pull requests merged in 2018-05, with the labels that each got.

#347 Handle the case where domains directory does not exist
  config.js
  dadi/lib/models/domain-manager.js
  test/acceptance/auth.js
  test/acceptance/cache.js
Labels: in progress

#346 Basic GIF support
  dadi/lib/handlers/image.js
  package.json
  test/acceptance/visual_manifest.json
  test/images/visual/baseline/measure1.gif
  test/unit/imagehandler.js
Labels: in progress

#357 Make config properties overridable at domain level
  config.js
  dadi/lib/auth/index.js
  dadi/lib/cache/index.js
  dadi/lib/controller/index.js
  dadi/lib/controller/recipe.js
  dadi/lib/handlers/css.js
  dadi/lib/handlers/default.js
  dadi/lib/handlers/image.js
  dadi/lib/handlers/js.js
  dadi/lib/index.js
  dadi/lib/storage/disk.js
  dadi/lib/storage/http.js
  dadi/lib/storage/missing.js
  dadi/lib/storage/s3.js
  package.json
  test/acceptance/auth.js
  test/acceptance/cache.js
  test/acceptance/controller.js
  test/acceptance/help.js
  test/acceptance/multi-domain.js
  test/acceptance/recipes.js
  test/assets/test-es6.js
  test/mocha.opts
  test/unit/jshandler.js
Labels: status: ready to merge

#361 Remove reliance on wget
  config.js
  dadi/lib/controller/index.js
  dadi/lib/handlers/image.js
  dadi/lib/help.js
  dadi/lib/storage/http.js
  package-lock.json
  package.json
  test/acceptance/controller.js
  test/acceptance/recipes.js
  test/acceptance/visual.js
Labels: type: enhancement
