Repository dadi/cdn, pull requests merged in 2018-04, with the labels that each got.

#320 Add domain-specific config and workspace
  README.md
  config.js
  dadi/lib/handlers/factory.js
  dadi/lib/index.js
  dadi/lib/models/route.js
  dadi/lib/models/workspace.js
  domains/testdomain.com/config/config.test.json
  package.json
  test/unit/config.js
  test/unit/workspace.js
Labels: in progress, status: ready to merge

#326 Use domain as part of cache key
  dadi/lib/cache/index.js
  dadi/lib/handlers/factory.js
  dadi/lib/handlers/image.js
  dadi/lib/models/route.js
  dadi/lib/storage/disk.js
  dadi/lib/storage/factory.js
  dadi/lib/storage/http.js
  dadi/lib/storage/missing.js
  dadi/lib/storage/s3.js
  domains/localhost/config/config.test.json
  domains/localhost/workspace/recipes/domain-recipe.json
  domains/testdomain.com/config/config.test.json
  domains/testdomain.com/workspace/recipes/sample-image-recipe.json
  package.json
  test/acceptance/help.js
  test/acceptance/multi-domain.js
  test/acceptance/recipes.js
  test/unit/cache.js
  test/unit/routes.js
  test/unit/storage.http.js
  test/unit/storage.s3.js
  workspace/recipes/sample-image-recipe.json
Labels: in progress, status: ready to merge

#325 Rename cache flush endpoint
  dadi/lib/auth/index.js
  dadi/lib/controller/index.js
  dadi/lib/help.js
  package.json
  test/acceptance/auth.js
  test/acceptance/flush.js
Labels: in progress, status: blocked

#327 Return 404 if domain is not configured
  dadi/lib/index.js
  dadi/lib/models/workspace.js
  test/acceptance/multi-domain.js
  test/unit/workspace.js
Labels: in progress, status: ready to merge

#328 Add acceptance tests for caching with multi-domain
  dadi/lib/cache/index.js
  dadi/lib/handlers/image.js
  dadi/lib/help.js
  test/acceptance/multi-domain.js
  test/unit/cache.js
  test/unit/jshandler.js
Labels: in progress

#329 Remove upload support
  README.md
  config.js
  dadi/lib/auth/index.js
  dadi/lib/controller/index.js
  dadi/lib/controller/post.js
  dadi/lib/handlers/image.js
  dadi/lib/storage/disk.js
  dadi/lib/storage/s3.js
Labels: in progress, type: breaking

#332 Watch domain-level workspace files
  config.js
  dadi/lib/index.js
  dadi/lib/models/domain-manager.js
  dadi/lib/models/workspace.js
  test/acceptance/controller.js
  test/acceptance/file-change-monitor.js
  test/acceptance/help.js
  test/acceptance/index.js
  test/unit/domain-manager.js
  test/unit/workspace.js
Labels: in progress

#336 Flush cache by domain
  config.js
  dadi/lib/cache/index.js
  dadi/lib/controller/index.js
  dadi/lib/index.js
  package.json
  test/acceptance/flush.js
  test/acceptance/help.js
  test/acceptance/multi-domain.js
Labels: in progress

#339 Allow controller plugins to set cache header
  dadi/lib/controller/index.js
  dadi/lib/handlers/plugin.js
  dadi/lib/help.js
  test/acceptance/plugins.js
  test/unit/plugins.js
Labels: in progress

#340 Allow recipes to specify remote path
  .travis.yml
  dadi/lib/handlers/factory.js
  dadi/lib/handlers/image.js
  dadi/lib/index.js
  dadi/lib/storage/factory.js
  dadi/lib/storage/http.js
  package.json
  test/acceptance/recipes.js
  test/unit/imagehandler.js
  test/unit/server.js
Labels: in progress, status: ready to merge
